project:
  type: website

website:
  title: "HCAM blog"
  
  page-footer:
    border: true
    
  navbar:
    left:
      - text: Main_Blog
        href: https://seoyeonc.github.io/sy_hub/
        
    right:
      - about.qmd
      - icon: github
        href: https://github.com/seoyeonc
        
  sidebar:
    style: "docked"
    search: true
    contents:
      - 1_studies.qmd
      - section: "**Research**"
        contents:
          - 2_research.qmd
      - section: "**Result**"
        contents:
          - 3_figure.qmd
        
format:
  html:
    theme: 
        light: flatly
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: false
    code-copy: false

